table = 'auth_permission'
fields = ['id', 'name', 'content_type_id', 'codename']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[4, u'Can add forecast', 2, u'add_forecast']
[5, u'Can change forecast', 2, u'change_forecast']
[6, u'Can delete forecast', 2, u'delete_forecast']
[7, u'Can add forecaster', 3, u'add_forecaster']
[8, u'Can change forecaster', 3, u'change_forecaster']
[9, u'Can delete forecaster', 3, u'delete_forecaster']
[10, u'Can add comment', 4, u'add_comment']
[11, u'Can change comment', 4, u'change_comment']
[12, u'Can delete comment', 4, u'delete_comment']
[13, u'Can add free comment', 5, u'add_freecomment']
[14, u'Can change free comment', 5, u'change_freecomment']
[15, u'Can delete free comment', 5, u'delete_freecomment']
[16, u'Can add karma score', 6, u'add_karmascore']
[17, u'Can change karma score', 6, u'change_karmascore']
[18, u'Can delete karma score', 6, u'delete_karmascore']
[19, u'Can add moderator deletion', 7, u'add_moderatordeletion']
[20, u'Can change moderator deletion', 7, u'change_moderatordeletion']
[21, u'Can delete moderator deletion', 7, u'delete_moderatordeletion']
[22, u'Can add user flag', 8, u'add_userflag']
[23, u'Can change user flag', 8, u'change_userflag']
[24, u'Can delete user flag', 8, u'delete_userflag']
[25, u'Can add flat page', 9, u'add_flatpage']
[26, u'Can change flat page', 9, u'change_flatpage']
[27, u'Can delete flat page', 9, u'delete_flatpage']
[28, u'Can add message', 10, u'add_message']
[29, u'Can change message', 10, u'change_message']
[30, u'Can delete message', 10, u'delete_message']
[31, u'Can add group', 11, u'add_group']
[32, u'Can change group', 11, u'change_group']
[33, u'Can delete group', 11, u'delete_group']
[34, u'Can add user', 12, u'add_user']
[35, u'Can change user', 12, u'change_user']
[36, u'Can delete user', 12, u'delete_user']
[37, u'Can add permission', 13, u'add_permission']
[38, u'Can change permission', 13, u'change_permission']
[39, u'Can delete permission', 13, u'delete_permission']
[40, u'Can add content type', 14, u'add_contenttype']
[41, u'Can change content type', 14, u'change_contenttype']
[42, u'Can delete content type', 14, u'delete_contenttype']
[43, u'Can add session', 15, u'add_session']
[44, u'Can change session', 15, u'change_session']
[45, u'Can delete session', 15, u'delete_session']
[46, u'Can add site', 16, u'add_site']
[47, u'Can change site', 16, u'change_site']
[48, u'Can delete site', 16, u'delete_site']
[49, u'Can add log entry', 17, u'add_logentry']
[50, u'Can change log entry', 17, u'change_logentry']
[51, u'Can delete log entry', 17, u'delete_logentry']
[52, u'Can add redirect', 18, u'add_redirect']
[53, u'Can change redirect', 18, u'change_redirect']
[54, u'Can delete redirect', 18, u'delete_redirect']
[55, u'Can add forecast item', 19, u'add_forecastitem']
[56, u'Can change forecast item', 19, u'change_forecastitem']
[57, u'Can delete forecast item', 19, u'delete_forecastitem']
[58, u'Can add actual temperature', 20, u'add_actualtemperature']
[59, u'Can change actual temperature', 20, u'change_actualtemperature']
[60, u'Can delete actual temperature', 20, u'delete_actualtemperature']
[61, u'Can add chart', 21, u'add_chart']
[62, u'Can change chart', 21, u'change_chart']
[63, u'Can delete chart', 21, u'delete_chart']
[70, u'Can add accuracy rating', 24, u'add_accuracyrating']
[71, u'Can change accuracy rating', 24, u'change_accuracyrating']
[72, u'Can delete accuracy rating', 24, u'delete_accuracyrating']
[73, u'Can add accuracy rating archive', 25, u'add_accuracyratingarchive']
[74, u'Can change accuracy rating archive', 25, u'change_accuracyratingarchive']
[75, u'Can delete accuracy rating archive', 25, u'delete_accuracyratingarchive']
[76, u'Can add actual temperature', 26, u'add_actualtemperature']
[77, u'Can change actual temperature', 26, u'change_actualtemperature']
[78, u'Can delete actual temperature', 26, u'delete_actualtemperature']
[79, u'Can add forecast item', 27, u'add_forecastitem']
[80, u'Can change forecast item', 27, u'change_forecastitem']
[81, u'Can delete forecast item', 27, u'delete_forecastitem']
[82, u'Can add forecast', 28, u'add_forecast']
[83, u'Can change forecast', 28, u'change_forecast']
[84, u'Can delete forecast', 28, u'delete_forecast']
]
