table = 'django_content_type'
fields = ['id', 'name', 'app_label', 'model']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[2, u'forecast', u'weather', u'forecast']
[3, u'forecaster', u'forecaster', u'forecaster']
[4, u'comment', u'comments', u'comment']
[5, u'free comment', u'comments', u'freecomment']
[6, u'karma score', u'comments', u'karmascore']
[7, u'moderator deletion', u'comments', u'moderatordeletion']
[8, u'user flag', u'comments', u'userflag']
[9, u'flat page', u'flatpages', u'flatpage']
[10, u'message', u'auth', u'message']
[11, u'group', u'auth', u'group']
[12, u'user', u'auth', u'user']
[13, u'permission', u'auth', u'permission']
[14, u'content type', u'contenttypes', u'contenttype']
[15, u'session', u'sessions', u'session']
[16, u'site', u'sites', u'site']
[17, u'log entry', u'admin', u'logentry']
[18, u'redirect', u'redirects', u'redirect']
[19, u'forecast item', u'weather', u'forecastitem']
[20, u'actual temperature', u'weather', u'actualtemperature']
[21, u'chart', u'charts', u'chart']
[24, u'accuracy rating', u'forecaster', u'accuracyrating']
[25, u'accuracy rating archive', u'forecaster', u'accuracyratingarchive']
[26, u'actual temperature', u'forecast', u'actualtemperature']
[27, u'forecast item', u'forecast', u'forecastitem']
[28, u'forecast', u'forecast', u'forecast']
]
